### ISSUE TITLE
LXDoNe production ready?

### ISSUE THREAD

**Issue by RubenBG7** [OpenNebula/addon-lxdone#2]
Hello! Has anyone tried this plugin? Can anyone confirm to me if it really supports OpenNebula and it works? Thank you so much.

**Comment by sergiojvg** [comment]
Hi Ruben. This addon has been powering our Data Center on [CUJAE University](http://cujae.edu.cu) for more than 6 month now, and, except for 3 KVM VMs, all of our VMs are LXD container deployed through OpenNebula 5.2.1 running on Ubuntu Xenial. We are still adding new functionalities but we haven't found any new bug in a while now. The only one remaining is related with VNC and is not critical, you can read about it [here](https://github.com/OpenNebula/addon-lxdone/blob/master/README.md#known-bugs). In case you encounter any issue during installation you can write it here or [email us](https://github.com/OpenNebula/addon-lxdone#developers) and we'll be happy to help.
Bests

**Comment by dann1** [comment]
If you don't trust the documentation you can always try it inside a Virtual Machine, as we do to develop new features.
