### ISSUE TITLE
Step 1.4.1 Drivers NOT FOUND

### ISSUE THREAD

**Issue by RubenBG7** [OpenNebula/addon-lxdone#3]
Somebody could say me if this plugin works?

**Comment by sergiojvg** [comment]
https://github.com/OpenNebula/addon-lxdone/issues/2

**Comment by dann1** [comment]
I don't understand, in step 1.4.1 we assumed you download a .zip file and extract it. Can you be more specific?

**Comment by dann1** [comment]
Human error
