### ISSUE TITLE
Missing or Incorrect Documentation in Setup Guide instruction

### ISSUE THREAD

**Issue by bmullan** [OpenNebula/addon-lxdone#51]
I'm using Ubuntu 18.04 on a KVM VM. 16GB ram, 4 cpu, 100GB disk

I was following the instructions to install addon-lxdone and got to the section:

> Follow KVM Node Installation, up to step 6.

So following the KVM Node installation I got to:

> To add OpenNebula repository on Debian/Ubuntu execute as root:

Found there is no Ubuntu 18.04 instruction so I just edited & used the 17.04 instruction to look like:

> echo "deb https://downloads.opennebula.org/repo/5.4/Ubuntu/**18.04** stable opennebula" > /etc/apt/sources.list.d/opennebula.list

Saved the change then did:

> sudo apt update

and got the following error:

> **The following packages have unmet dependencies:
>  opennebula-node : Depends: opennebula-common (= 5.4.1-1) but 5.6.1-1 is to be installed
> E: Unable to correct problems, you have held broken packages.**

**so I changed the /etc/atp/sources.list.d/opennebula/list to:

> **deb https://downloads.opennebula.org/repo/5.6.1/Ubuntu/18.04 stable opennebula**

and then "sudo apt update" worked..!**

The next documentation problem I saw was with  **Step 4. Configure Passwordless SSH**

Following the documentation we've not yet created any LXD container "nodes" yet!  So I am not sure how someone installing LXDone would accomplish the:

> To create the known_hosts file, we have to execute this command as user oneadmin in the Front-end with all the node names and the Front-end name as parameters:
> 
> **ssh-keyscan <frontend> <node1> <node2> <node3> ... >> /var/lib/one/.ssh/known_hosts**

Next, again not sure what someone installing LXDone does for:  

> **Step 5. Networking Configuration**

As installation of LXD (**sudo apt install lxd** -or- **sudo snap install lxd**) followed by the execution of **sudo lxd init**  usually creates the **lxdbr0** bridge...  I am **not** sure whether to create a BR0 bridge in Step 5 or not ???

However... since step  **2.1 Install required packages**  looks like thats where LXD gets installed and in step **2.5.1 Configure the LXD daemon** it **does do an LXD INIT** I am guessing that lxdbr0 will work

**In section 2.1 Install Required Packages**

There needs to be an 18.04 identical to the 16.04 except replace **xenial** with **bionic**:

apt install lxd lxd-tools python-pylxd/bionic-updates \
                criu bridge-utils \
                python-ws4py python-pip

In section 2.1 it says:

**> Check that pylxd is >= 2.0.5 or LXDoNe will not work correctly.
> 
> dpkg -s python-pylxd | grep 2.0.5 || echo "ERROR pylxd version not 2.05"**

But the python-pylxd that installed earlier is **2.2.6-0ubuntu1.1** so **the above ERROR is incorrect** I believe!

When Creating a Virtual Network where instructions say:

> **First IP/MAC address: some private IP available on the network.**

I input **10.66.154.1** which is the IP of my LXDBR0 bridge and get an error:

> **One or more required fields are missing or malformed**

So I thought I'd try **10.66.154.2** ... same error!

Now I am stuck as I don't know what it wants here.

So I'm going to stop here until I get a reply with advice of what to enter here.

I've got to say that overall ... your instructions are **VERY** good other than the above info I've documented.

Really looking forward to trying this.

Brian

Brian

**Comment by dann1** [comment]
Ubuntu 18.04 is not currently supported as virtualization node

**Comment by bmullan** [comment]
That's too bad...
I'd been following this guide to install OpenNebula on 18.04 and it was very accurate in itself and I did get OpenNebula installed OK.

It was just during the install of LXDone that I encountered what I'd documented.

Anyway, when you get around to 18.04 perhaps some of the above will save you some typing.

**Comment by dann1** [comment]
Hopefully for us there will be official LXD with Ubuntu 18.04 and lxd3 on OpenNebula  very soon :)

https://github.com/OpenNebula/one/issues/1684

https://github.com/OpenNebula/one/tree/feature-1684

**Comment by bmullan** [comment]
Daniel

If you need any beta testers for the 18.04 and LXD 3.x implementation both
myself and another long time LXD user that is a friend of mine would be
interested.

Both of us are novices to OpenNebula but both of us are long time Ubuntu
and more importantly LXD users.

We are both very anxious to see the LXDoNe successful with OpenNebula and
would glad to help where we can.

Brian

**Comment by dann1** [comment]
Right now the code I have on https://github.com/OpenNebula/one/tree/feature-1684 is functional, it just lacks a specific feature, but luckly it's optional and doesn't break the usual operation. I haven't made an automated install process yet using packages nor a readme showing how to, but what you could do is install opennebula as usual and add the virtualization drivers in the branch to the node, very similar with lxdone. Next week I'll have ready a guide to setup the LXD drivers, and finish the installation/packaging of them. 
If you are willing to tinker the setup process through try and error, then you are welcome, if not, I'll promise on monday I'll have the beta setup guide ready. 

Thanks a lot for offering to try the new driver, though LXDoNe (I made a better driver from scratch, with cools stuff [like this one](https://github.com/lxc/lxd/issues/2574) ) won't be maintained anymore, for obvious reasons. If you want to submit feedback please use the forum, that way more people can get to know your experiences, and hopefully I'll get more testers :)

**Comment by bmullan** [comment]
Daniel...


*re..*
*"though LXDoNe ...  won't be maintained anymore, for obvious reasons"*

Not sure what the obvious reasons are as I indicated I'm newly introduced
to OpenNebula ...  I am assuming the "obvious reasons" are your time
involvement?

That is really too bad as I think myself & the friend I just got interested
in the combination of OpenNebula and LXD both got pretty excited about
finally having a good management/orchestration system for large scale LXD
deployment.
The fact that OpenNebula could also deploy/manage VM's etc just makes the
overall hybrid solution very attractive.

My friend is an engineer with a very large Tech corporation and they use
LXD alot but currently also utilize vmware/vcenter etc for VM
management.
A solution combining OpenNebula LXD/vmware sounded very attractive to him
and so I got him pretty excited to see what you were going to do with this
improved LXDoNe.

If however, the future maintenance is going to disappear that may put a
damper on his enthusiasm.

Anyway, I think both of use will still be ready to try things out next week
when you get things more wrapped up.

Thanks
Brian

**Comment by dann1** [comment]
Sorry you misunderstood, lxdone won't be maintained anymore because it's an addon, I'm working on official LXD from scratch. What I mean is, these are new drivers based on the experiences of LXDoNe, it's not a new version of LXDoNe.

> though LXDoNe ...  won't be maintained anymore, for obvious reasons

It won't be maintained cause it will be replaced by the official drivers.

**Comment by bmullan** [comment]
WHEW...  :-)

Yes I did misunderstand... great !!!   Glad I stupidly misunderstood that
and asked the question.

Thanks again and now we are back to being more than excited for next week.

Brian

**Comment by bmullan** [comment]
Its been about a month and I'm curious about the progress for the update of
LXDoNe and Ubuntu 18.04 for ONE?

Any tentative release schedule available yet?

thanks

Brian Mullan

**Comment by dann1** [comment]
Well, there's no fixed release date, but it will come out with the 5.8 one release. You can try the code in https://github.com/OpenNebula/one/tree/feature-1684, the documentation is https://github.com/dann1/docs/tree/feature-1684 and the package builder is https://github.com/OpenNebula/packages/tree/feature-1684. You can try to hack an official KVM node and a frontend to make it work with the official LXD drivers, sort of what we do with LXDoNe, or ... you can give it a try to https://github.com/dann1/docs/blob/master/source/integration/references/compile.rst set up a LXD scenario. The code is functional we are in bug fix mode right now and tomorrow there will be a live demo on the [opennebula conf](http://2018.opennebulaconf.com/). I imagine the videos will be later uploaded to [youtube](https://www.youtube.com/user/OpenNebula)
